#!/bin/bash

##########################################
echo '=======================================opening up IPTables to allow intenet comms===================================='

rm /etc/iptables/rules.v4
sudo iptables-save > /etc/iptables/rules.v4

echo '# Generated by iptables-save v1.8.7 on Thu Mar  9 11:37:17 2023' >> /etc/iptables/rules.v4
echo '*filter' >> /etc/iptables/rules.v4
echo ':INPUT DROP [130:14631]' >> /etc/iptables/rules.v4
echo ':FORWARD ACCEPT [0:0]' >> /etc/iptables/rules.v4
echo ':OUTPUT ACCEPT [0:0]' >> /etc/iptables/rules.v4
echo '#Allow Loopback  << the following two lines allow local loopback connection required for the reverse telnet to the device via Ser2Net.' >> /etc/iptables/rules.v4
echo '-A INPUT -i lo -j ACCEPT' >> /etc/iptables/rules.v4
echo '-A OUTPUT -o lo -j ACCEPT' >> /etc/iptables/rules.v4
echo '# << The following entries only allow SSH on port 4044 to this host over the internet from only secured RWS site Brno and Maidenhead public IP’s.' >> /etc/iptables/rules.v4
echo '-A INPUT -s 192.168.0.0/16 -p tcp -m tcp --dport 4044 -j ACCEPT' >> /etc/iptables/rules.v4
echo '-A INPUT -j ACCEPT' >> /etc/iptables/rules.v4
echo '-A OUTPUT -j ACCEPT' >> /etc/iptables/rules.v4
echo '#-A INPUT -j DROP' >> /etc/iptables/rules.v4
echo 'COMMIT' >> /etc/iptables/rules.v4
echo '# Completed on Thu Mar  9 11:37:17 2023' >> /etc/iptables/rules.v4

iptables-restore < /etc/iptables/rules.v4
echo '<<<Success>>>'
########################################
echo '=======================================Performing update and system upgrades========================================='
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get -y install cron -y
sudo apt-get install ser2net nano iptables-persistent telnet rsyslog -y
echo '<<<Success>>>' 
#######################################
echo '=======================================Re-instating Hardened IPtables==============================================='
rm /etc/iptables/rules.v4
sudo iptables-save > /etc/iptables/rules.v4
echo '# Generated by iptables-save v1.8.7 on Thu Mar  9 11:37:17 2023' >> /etc/iptables/rules.v4
echo '*filter' >> /etc/iptables/rules.v4
echo ':INPUT DROP [130:14631]' >> /etc/iptables/rules.v4
echo ':FORWARD ACCEPT [0:0]' >> /etc/iptables/rules.v4
echo ':OUTPUT ACCEPT [0:0]' >> /etc/iptables/rules.v4
echo '#Allow Loopback  << the following two lines allow local loopback connection required for the reverse telnet to the device via Ser2Net.' >> /etc/iptables/rules.v4
echo '-A INPUT -i lo -j ACCEPT' >> /etc/iptables/rules.v4
echo '-A OUTPUT -o lo -j ACCEPT' >> /etc/iptables/rules.v4
echo '# << The following entries only allow SSH on port 4044 to this host over the internet from only secured RWS site Brno and Maidenhead public IP’s.' >> /etc/iptables/rules.v4
echo '-A INPUT -s 192.168.0.0/16 -p tcp -m tcp --dport 4044 -j ACCEPT' >> /etc/iptables/rules.v4
echo '#-A INPUT -j ACCEPT' >> /etc/iptables/rules.v4
echo '#-A OUTPUT -j ACCEPT' >> /etc/iptables/rules.v4
echo '-A INPUT -j DROP' >> /etc/iptables/rules.v4
echo 'COMMIT' >> /etc/iptables/rules.v4
echo '# Completed on Thu Mar  9 11:37:17 2023' >> /etc/iptables/rules.v4
iptables-restore < /etc/iptables/rules.v4
echo '<<<Success>>>'
